### ISSUE TITLE
support usage on pandas 1.20

### ISSUE THREAD

**Issue by geoHeil** [elastic/eland#339]
`import eland ` fails on Windows with:

```
Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:30:06) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import eland
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\my_env\lib\site-packages\eland\__init__.py", line 29, in <module>
    from .dataframe import DataFrame
  File "C:\ProgramData\Anaconda3\envs\my_env\lib\site-packages\eland\dataframe.py", line 36, in <module>
    import eland.plotting as gfx
  File "C:\ProgramData\Anaconda3\envs\my_env\lib\site-packages\eland\plotting\__init__.py", line 25, in <module>
    from eland.plotting._core import ed_hist_frame, ed_hist_series
  File "C:\ProgramData\Anaconda3\envs\my_env\lib\site-packages\eland\plotting\_core.py", line 18, in <module>
    from eland.plotting._matplotlib.hist import hist_frame, hist_series
  File "C:\ProgramData\Anaconda3\envs\my_env\lib\site-packages\eland\plotting\_matplotlib\__init__.py", line 25, in <module>
    from eland.plotting._matplotlib.hist import hist_frame, hist_series
  File "C:\ProgramData\Anaconda3\envs\my_env\lib\site-packages\eland\plotting\_matplotlib\hist.py", line 21, in <module>
    from pandas.plotting._matplotlib.tools import _flatten, _set_ticks_props, _subplots
ImportError: cannot import name '_flatten' from 'pandas.plotting._matplotlib.tools' (C:\ProgramData\Anaconda3\envs\my_env\lib\site-packages\pandas\plotting\_matplotlib\tools.py)
```

for pandas 1.1.5 it works just fine

**Comment by sethmlarson** [comment]
Support for pandas 1.2 landed on `master` via https://github.com/elastic/eland/pull/336 already, just hasn't been released. Can look at getting a release out.
