### ISSUE TITLE
Issue when loading BERT model

### ISSUE THREAD

**Issue by ColeDCrawford** [elastic/eland#519]
Trying to load a HuggingFace model. ES 8.5.0, eland v8.3.0 (latest).

```
root@123db2795af8:/app# eland_import_hub_model --ca-certs /usr/share/elasticsearch/config/certs/ca/ca.crt --url https://elastic:PASSWORD@es01:9200/ --hub-model-id Charangan/MedBERT --task-type text_embedding --start
2023-03-02 07:28:01,267 INFO : Establishing connection to Elasticsearch
2023-03-02 07:28:01,281 INFO : Connected to cluster named 'dle-elastic-cluster' (version: 8.5.0)
2023-03-02 07:28:01,282 INFO : Loading HuggingFace transformer tokenizer and model 'Charangan/MedBERT'
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 417/417 [00:00<00:00, 368kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 208k/208k [00:00<00:00, 1.92MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 125/125 [00:00<00:00, 225kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 682/682 [00:00<00:00, 650kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 416M/416M [00:52<00:00, 8.35MB/s]
Some weights of the model checkpoint at Charangan/MedBERT were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Asking to pad to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no padding.
Traceback (most recent call last):
  File "/usr/local/bin/eland_import_hub_model", line 204, in <module>
    model_exists = es.options(ignore_status=404).ml.get_trained_models(model_id=ptm.model_id).meta.status == 200
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/ml.py", line 2164, in get_trained_models
    return self.perform_request(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 389, in perform_request
    return self._client.perform_request(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'no handler found for uri [/_ml/trained_models/charangan__medbert] and method [GET]', 'no handler found for uri [/_ml/trained_models/charangan__medbert] and method [GET]')
```

Any ideas? I've tried a couple different models, hit the same error with all of them.

**Comment by ColeDCrawford** [comment]
Same error when trying with Docker a la the instructions in the README.
